/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.*;
import java.util.ResourceBundle;


/**
 *
 * @author shrutiatitkar
 */
public class CanvasGUI extends javax.swing.JFrame {
    private DrawingCanvas drawingCanvas;
    /**
     * Creates new form CanvasGUI
     */
    Client client;
    User currentUser;

    ResourceBundle bundle;
    public CanvasGUI(Client client, User user, ResourceBundle bundle) {
        this.client = client;
        this.bundle = bundle;
        currentUser = user;
        initComponents();
        drawingCanvas = new DrawingCanvas();
        drawingCanvas.setBackground(Color.WHITE);
        Canvas.add(drawingCanvas);
        drawingCanvas.setBounds(Canvas.getBounds());
        drawingCanvas.setVisible(true);

        // Add ChangeListener to ColorSwatch
        ColorSwatch.getSelectionModel().addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                drawingCanvas.setCurrentColor(ColorSwatch.getColor());
            }
        });

        PenBtnActionPerformed(null);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        PenBtn = new javax.swing.JButton();
        EraserBtn = new javax.swing.JButton();
        ColorSwatch = new javax.swing.JColorChooser();
        SaveBtn = new javax.swing.JButton();
        canvas1 = new java.awt.Canvas();
        Canvas = new javax.swing.JPanel();
        EraserBtn1 = new javax.swing.JButton();

        PenBtn.setText(bundle.getString("canvas.pen"));
        PenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenBtnActionPerformed(evt);
            }
        });

        EraserBtn.setText(bundle.getString("canvas.eraser"));
        EraserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EraserBtnActionPerformed(evt);
            }
        });

        ColorSwatch.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                ColorSwatchInputMethodTextChanged(evt);
            }
        });

        SaveBtn.setText(bundle.getString("canvas.save"));
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CanvasLayout = new javax.swing.GroupLayout(Canvas);
        Canvas.setLayout(CanvasLayout);
        CanvasLayout.setHorizontalGroup(
            CanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
        );
        CanvasLayout.setVerticalGroup(
            CanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        EraserBtn1.setText(bundle.getString("canvas.erase_all"));
        EraserBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EraserBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Canvas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(ColorSwatch, javax.swing.GroupLayout.PREFERRED_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(PenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EraserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EraserBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EraserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EraserBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Canvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ColorSwatch, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>                        

    private void PenBtnActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
         drawingCanvas.setPenSelected(true);
         drawingCanvas.setEraserSelected(false);
    }                                      

    private void EraserBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        drawingCanvas.setPenSelected(false);
        drawingCanvas.setEraserSelected(true);
    }                                         

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {
        drawingCanvas.saveDrawing();
        UploadGUI uGUI = new UploadGUI(client, currentUser, bundle);
        uGUI.show();
        // TODO add your handling code here:
    }                                       

    private void ColorSwatchInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void EraserBtn1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        drawingCanvas.clearDrawing();
      
    }                                          

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JPanel Canvas;
    private javax.swing.JColorChooser ColorSwatch;
    private javax.swing.JButton EraserBtn;
    private javax.swing.JButton EraserBtn1;
    private javax.swing.JButton PenBtn;
    private javax.swing.JButton SaveBtn;
    private java.awt.Canvas canvas1;
    // End of variables declaration                   
}
